name: Deploy Memory Test Project

on:
  push:
    branches:
      - main # Deploy only from the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (if needed for a build step, though it's not required for your static HTML/CSS/JS)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm install
        fi

    - name: Build (if needed)
      run: |
        if [ -f build ]; then
          npm run build
        fi

    - name: Install Aliyun OSS CLI (Corrected Method)
      run: |
        # Install dependencies
        sudo apt-get update && sudo apt-get install -y wget curl unzip

        # Download the OSS CLI using a correct installation method (via Aliyun)
        wget https://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64 -O ossutil

        # Grant execute permissions
        chmod +x ossutil

        # Move it to a directory in your PATH
        sudo mv ossutil /usr/local/bin/

        # Verify the installation
        ossutil version

    - name: Configure OSS CLI
      run: |
        ossutil config --access-key-id ${{ secrets.OSS_ACCESS_KEY_ID }} --access-key-secret ${{ secrets.OSS_ACCESS_KEY_SECRET }} --endpoint ${{ secrets.OSS_ENDPOINT }}

    - name: Deploy to OSS (or other static hosting platform)
      run: |
        # Upload files to your OSS bucket (adjust path to your actual files)
        ossutil cp --recursive ./path/to/your/files oss://your-bucket-name/

    - name: Finalize Deployment
      run: |
        echo "Deployment completed successfully!"
