name: Deploy Memory Test Project

on:
  push:
    branches:
      - main # Deploy only from the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (if needed for a build step, though it's not required for your static HTML/CSS/JS)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm install
        fi

    - name: Build (if needed)
      run: |
        if [ -f build ]; then
          npm run build
        fi

    - name: Install Aliyun OSS CLI (Corrected Method)
      run: |
        # Install dependencies for building and downloading
        sudo apt-get update && sudo apt-get install -y wget curl unzip

        # Download the latest OSS CLI release from GitHub
        wget https://github.com/aliyun/aliyun-oss-cli/releases/download/v3.0.0/aliyun-oss-cli-linux-amd64-v3.0.0.tar.gz

        # Extract and move the binary to a directory in your $PATH (e.g., /usr/local/bin)
        tar -xzvf aliyun-oss-cli-linux-amd64-v3.0.0.tar.gz
        sudo mv aliyun-oss-cli-linux-amd64 /usr/local/bin/aliyun-oss-cli

        # Verify OSS CLI is installed correctly
        aliyun-oss-cli --version

    - name: Configure OSS CLI
      run: |
        aliyun oss config --access-key-id ${{ secrets.OSS_ACCESS_KEY_ID }} --access-key-secret ${{ secrets.OSS_ACCESS_KEY_SECRET }} --endpoint ${{ secrets.OSS_ENDPOINT }}

    - name: Deploy to OSS (or other static hosting platform)
      run: |
        # Upload files to your OSS bucket (adjust path to your actual files)
        aliyun oss cp --recursive ./path/to/your/files oss://your-bucket-name/

    - name: Finalize Deployment
      run: |
        echo "Deployment completed successfully!"
