name: Build and Deploy Website

on:
  push:
    branches:
      - main  # Ensure it runs on push to 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (optional if needed)
        run: npm install  # Only if you need to install dependencies

      - name: Copy files to dist
        run: |
          mkdir -p dist
          cp -r * dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
